
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Admin
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setTitle(" Laboratorio 7");
        this.setLocationRelativeTo(null);
        br = new administrarBarra(pg_registro);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_OpcionesRegistro = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();
        jd_Artista = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cb_artistas = new javax.swing.JComboBox<>();
        tf_userArtista = new javax.swing.JTextField();
        tf_contraArtista = new javax.swing.JTextField();
        tf_nombreArtista = new javax.swing.JTextField();
        tf_generoArtista = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        bt_registrarArtista = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        pg_registro = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        jd_admin = new javax.swing.JDialog();
        bt_removeArtistas = new javax.swing.JButton();
        bt_removeUsuarios = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jd_artistasAdmin = new javax.swing.JDialog();
        jd_usuarioRegistrar = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tf_userUsuario = new javax.swing.JTextField();
        tf_contraUsuario = new javax.swing.JTextField();
        tf_nombreUsuario = new javax.swing.JTextField();
        tf_edadUsuario = new javax.swing.JTextField();
        bt_registrarUsuario = new javax.swing.JButton();
        pg_usuario = new javax.swing.JProgressBar();
        jLabel12 = new javax.swing.JLabel();
        bt_ingresare = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_usuarioLogin = new javax.swing.JTextField();
        tf_passLogin = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jd_OpcionesRegistro.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Artista");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jd_OpcionesRegistro.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 140, 40));

        jButton2.setText("Usuario");
        jd_OpcionesRegistro.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 130, 40));

        jButton3.setText("Regresar");
        jd_OpcionesRegistro.getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 120, 40));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white2.png"))); // NOI18N
        jd_OpcionesRegistro.getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 430));

        jd_Artista.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel6.setText("Usuario");
        jd_Artista.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 90, 30));

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel7.setText("Contraseña");
        jd_Artista.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel8.setText("Nombre");
        jd_Artista.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        jLabel9.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel9.setText("Tipo de Artitas");
        jd_Artista.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        cb_artistas.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        cb_artistas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "*Artistas*", "Bandas", "Solistas" }));
        jd_Artista.getContentPane().add(cb_artistas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 120, 30));
        jd_Artista.getContentPane().add(tf_userArtista, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 120, -1));
        jd_Artista.getContentPane().add(tf_contraArtista, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 120, -1));
        jd_Artista.getContentPane().add(tf_nombreArtista, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 120, -1));
        jd_Artista.getContentPane().add(tf_generoArtista, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 120, -1));

        jLabel10.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel10.setText("Genero musical");
        jd_Artista.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        bt_registrarArtista.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        bt_registrarArtista.setText("Registrar");
        bt_registrarArtista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_registrarArtistaMouseClicked(evt);
            }
        });
        jd_Artista.getContentPane().add(bt_registrarArtista, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 120, 30));

        jButton4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jButton4.setText("Regresar");
        jd_Artista.getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 100, 30));

        pg_registro.setMaximum(5);
        jd_Artista.getContentPane().add(pg_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 240, 20));
        jd_Artista.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 400));

        jd_admin.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_removeArtistas.setText("Eliminar Artistas");
        bt_removeArtistas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_removeArtistasMouseClicked(evt);
            }
        });
        jd_admin.getContentPane().add(bt_removeArtistas, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, -1, -1));

        bt_removeUsuarios.setText("Eliminar Usuarios");
        jd_admin.getContentPane().add(bt_removeUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white2.png"))); // NOI18N
        jd_admin.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 430));

        javax.swing.GroupLayout jd_artistasAdminLayout = new javax.swing.GroupLayout(jd_artistasAdmin.getContentPane());
        jd_artistasAdmin.getContentPane().setLayout(jd_artistasAdminLayout);
        jd_artistasAdminLayout.setHorizontalGroup(
            jd_artistasAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_artistasAdminLayout.setVerticalGroup(
            jd_artistasAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jd_usuarioRegistrar.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel13.setText("Usuario");
        jd_usuarioRegistrar.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jLabel14.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel14.setText("Contraseña");
        jd_usuarioRegistrar.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        jLabel15.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel15.setText("Nombre");
        jd_usuarioRegistrar.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        jLabel16.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel16.setText("Edad");
        jd_usuarioRegistrar.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 50, -1));
        jd_usuarioRegistrar.getContentPane().add(tf_userUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 100, -1));
        jd_usuarioRegistrar.getContentPane().add(tf_contraUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 100, -1));
        jd_usuarioRegistrar.getContentPane().add(tf_nombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 100, -1));
        jd_usuarioRegistrar.getContentPane().add(tf_edadUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 100, -1));

        bt_registrarUsuario.setText("Registrar");
        bt_registrarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_registrarUsuarioMouseClicked(evt);
            }
        });
        jd_usuarioRegistrar.getContentPane().add(bt_registrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 170, 30));
        jd_usuarioRegistrar.getContentPane().add(pg_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 150, 20));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white2.png"))); // NOI18N
        jd_usuarioRegistrar.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 510));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_ingresare.setText("Ingresar");
        bt_ingresare.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_ingresareMouseClicked(evt);
            }
        });
        getContentPane().add(bt_ingresare, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 150, 40));

        jLabel1.setText("Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        jLabel3.setText("Contraseña");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));
        getContentPane().add(tf_usuarioLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 110, 30));
        getContentPane().add(tf_passLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 110, 30));

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Aun no estas registrado? Registrate");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 210, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        jd_OpcionesRegistro.pack();
        jd_OpcionesRegistro.setModal(true);
        jd_OpcionesRegistro.setLocationRelativeTo(this);
        jd_OpcionesRegistro.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void bt_registrarArtistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_registrarArtistaMouseClicked

        if (cb_artistas.getSelectedIndex() == 1) {
            int nIntegrantes = Integer.parseInt(JOptionPane.showInputDialog(" Ingrese numero de integrantes"));
            artistas.add(new Bandas(nIntegrantes, tf_userArtista.getText(), tf_contraArtista.getText(), tf_nombreArtista.getText(), tf_generoArtista.getText()));
            Bandas o = new Bandas(nIntegrantes, tf_userArtista.getText(), tf_contraArtista.getText(), tf_nombreArtista.getText(), tf_generoArtista.getText());
            bands.add(new Bandas(nIntegrantes, tf_userArtista.getText(), tf_contraArtista.getText(), tf_nombreArtista.getText(), tf_generoArtista.getText()));

            adminBandas ap = new adminBandas("./bandas.cbm");
            ap.cargarArchivoBandas();
            ap.setBanda(o);
            ap.escribirArchivoBandas();
            br.start();

            tf_userArtista.setText("");
            tf_contraArtista.setText("");
            tf_nombreArtista.setText("");
            tf_generoArtista.setText("");

        } else if (cb_artistas.getSelectedIndex() == 2) {
            int edad = Integer.parseInt(JOptionPane.showInputDialog(" Ingrese la edad"));
            Artistas k = new Solistas(edad, tf_userArtista.getText(), tf_contraArtista.getText(), tf_nombreArtista.getText(), tf_generoArtista.getText());
            Solistas p = new Solistas(edad, tf_userArtista.getText(), tf_contraArtista.getText(), tf_nombreArtista.getText(), tf_generoArtista.getText());
            bands.add(new Bandas(edad, tf_userArtista.getText(), tf_contraArtista.getText(), tf_nombreArtista.getText(), tf_generoArtista.getText()));
            adminSolistas ss = new adminSolistas("./solistas.cbm");
            ss.cargarArchivoSolistas();
            ss.setySolista(p);
            ss.escribirArchivoSolistas();
            br.start();
            tf_userArtista.setText("");
            tf_contraArtista.setText("");
            tf_nombreArtista.setText("");
            tf_generoArtista.setText("");

        } else if (cb_artistas.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Opcion incorrecta");
        }


    }//GEN-LAST:event_bt_registrarArtistaMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        jd_OpcionesRegistro.setVisible(true);
        jd_Artista.pack();
        jd_Artista.setModal(true);
        jd_Artista.setLocationRelativeTo(this);
        jd_Artista.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void bt_ingresareMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_ingresareMouseClicked
        String userr = tf_usuarioLogin.getText();
        String pass = tf_passLogin.getText();
        adminBandas ap = new adminBandas("./bandas.cbm");
        ap.cargarArchivoBandas();
        adminSolistas ss = new adminSolistas("./solistas.cbm");
        ss.cargarArchivoSolistas();
        adminUsuarios pp = new adminUsuarios("./usuarios.cbm");
        pp.cargarArchivoUsuario();

        for (int i = 0; i < ap.getBands().size(); i++) {
            if (ap.getBands().get(i).getUsuario().equals(userr) && ap.getBands().get(i).getContraseña().equals(pass)) {
                JOptionPane.showMessageDialog(this, " Es una banda");
                break;
            }

        }
        for (int i = 0; i < ss.getSolis().size(); i++) {

            if (ss.getSolis().get(i).getUsuario().equals(userr) && ss.getSolis().get(i).getContraseña().equals(pass)) {
                JOptionPane.showMessageDialog(this, " Es un solista");
                break;
            }
        }

        for (int i = 0; i < usiss.size(); i++) {
            if (pp.getUsis().get(i).getUsuario().equals(userr) && pp.getUsis().get(i).getPassword().equals(pass)) {
                JOptionPane.showMessageDialog(this, " Es una banda");
                break;
            }

        }
        if (userr.equals("leobanegas") && pass.equals("99")) {
            jd_admin.pack();
            jd_admin.setModal(true);
            jd_admin.setLocationRelativeTo(this);
            jd_admin.setVisible(true);

        }


    }//GEN-LAST:event_bt_ingresareMouseClicked

    private void bt_removeArtistasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_removeArtistasMouseClicked
        jd_admin.setVisible(false);
        jd_artistasAdmin.pack();
        jd_artistasAdmin.setModal(true);
        jd_artistasAdmin.setLocationRelativeTo(this);
        jd_artistasAdmin.setVisible(true);
    }//GEN-LAST:event_bt_removeArtistasMouseClicked

    private void bt_registrarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_registrarUsuarioMouseClicked
        int edad = Integer.parseInt(tf_edadUsuario.getText());
        Usuarios u = new Usuarios(tf_userUsuario.getText(), tf_contraUsuario.getText(), tf_nombreUsuario.getText(), tf_edadUsuario.getText());
        bands.add(new Bandas(edad, tf_userArtista.getText(), tf_contraArtista.getText(), tf_nombreArtista.getText(), tf_generoArtista.getText()));
        adminUsuarios pp = new adminUsuarios("./usuarios.cbm");
        pp.cargarArchivoUsuario();
        pp.setUsuarios(u);
        pp.escribirArchivoUsuario();
        JOptionPane.showMessageDialog(this, "Solista guardado exitosamente");
    }//GEN-LAST:event_bt_registrarUsuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_ingresare;
    private javax.swing.JButton bt_registrarArtista;
    private javax.swing.JButton bt_registrarUsuario;
    private javax.swing.JButton bt_removeArtistas;
    private javax.swing.JButton bt_removeUsuarios;
    private javax.swing.JComboBox<String> cb_artistas;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JDialog jd_Artista;
    private javax.swing.JDialog jd_OpcionesRegistro;
    private javax.swing.JDialog jd_admin;
    private javax.swing.JDialog jd_artistasAdmin;
    private javax.swing.JDialog jd_usuarioRegistrar;
    private javax.swing.JProgressBar pg_registro;
    private javax.swing.JProgressBar pg_usuario;
    private javax.swing.JTextField tf_contraArtista;
    private javax.swing.JTextField tf_contraUsuario;
    private javax.swing.JTextField tf_edadUsuario;
    private javax.swing.JTextField tf_generoArtista;
    private javax.swing.JTextField tf_nombreArtista;
    private javax.swing.JTextField tf_nombreUsuario;
    private javax.swing.JPasswordField tf_passLogin;
    private javax.swing.JTextField tf_userArtista;
    private javax.swing.JTextField tf_userUsuario;
    private javax.swing.JTextField tf_usuarioLogin;
    // End of variables declaration//GEN-END:variables
ArrayList<Bandas> bands = new ArrayList();
    ArrayList<Solistas> solistas = new ArrayList();

    ArrayList<Artistas> artistas = new ArrayList();
    administrarBarra br;

    ArrayList<Usuarios> usiss = new ArrayList();
}
